# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/robdj/Desktop/hdmi_pass_through_ZyboZ7-10-master/dvipass/dvipass.srcs/sources_1/ip/clk_wiz_125M_200M/clk_wiz_125M_200M.xci
# IP: The module: 'clk_wiz_125M_200M' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/robdj/Desktop/hdmi_pass_through_ZyboZ7-10-master/dvipass/dvipass.gen/sources_1/ip/clk_wiz_125M_200M/clk_wiz_125M_200M_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_125M_200M'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/robdj/Desktop/hdmi_pass_through_ZyboZ7-10-master/dvipass/dvipass.gen/sources_1/ip/clk_wiz_125M_200M/clk_wiz_125M_200M.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_125M_200M'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/robdj/Desktop/hdmi_pass_through_ZyboZ7-10-master/dvipass/dvipass.gen/sources_1/ip/clk_wiz_125M_200M/clk_wiz_125M_200M_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_125M_200M'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/robdj/Desktop/hdmi_pass_through_ZyboZ7-10-master/dvipass/dvipass.srcs/sources_1/ip/clk_wiz_125M_200M/clk_wiz_125M_200M.xci
# IP: The module: 'clk_wiz_125M_200M' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/robdj/Desktop/hdmi_pass_through_ZyboZ7-10-master/dvipass/dvipass.gen/sources_1/ip/clk_wiz_125M_200M/clk_wiz_125M_200M_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_125M_200M'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/robdj/Desktop/hdmi_pass_through_ZyboZ7-10-master/dvipass/dvipass.gen/sources_1/ip/clk_wiz_125M_200M/clk_wiz_125M_200M.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_125M_200M'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/robdj/Desktop/hdmi_pass_through_ZyboZ7-10-master/dvipass/dvipass.gen/sources_1/ip/clk_wiz_125M_200M/clk_wiz_125M_200M_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_125M_200M'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
